// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $Form from "./islands/Form.tsx";
import * as $FormStates from "./islands/FormStates.tsx";
import * as $TermModal from "./islands/TermModal.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/Form.tsx": $Form,
    "./islands/FormStates.tsx": $FormStates,
    "./islands/TermModal.tsx": $TermModal,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
